from __future__ import annotations

from pathlib import Path
from typing import Iterable, List, Optional, Sequence

import numpy as np
from PIL import Image
import torch
import torch.nn as nn
from torch.utils.data import ConcatDataset, Dataset


def infer_dddr_image_size(dataset_name: str) -> int:
    if dataset_name in {"cifar10", "cifar100"}:
        return 32
    if dataset_name in {"tiny_imagenet", "tinyimagenet200"}:
        return 64
    raise ValueError(
        f"DDDR adaptation currently supports cifar10/cifar100/tiny_imagenet-style synthetic replay, got: {dataset_name}"
    )


class DDDRProjectionHead(nn.Module):
    def __init__(self, in_dim: int, hidden_dim: int = 4096, out_dim: int = 256) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, out_dim),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class SupConLoss(nn.Module):
    """
    Copied in spirit from the released DDDR code.
    Input shape: [bsz, n_views, dim]
    """
    def __init__(self, temperature: float = 0.07, contrast_mode: str = "all", base_temperature: float = 0.07):
        super().__init__()
        self.temperature = float(temperature)
        self.contrast_mode = contrast_mode
        self.base_temperature = float(base_temperature)

    def forward(self, features: torch.Tensor, labels: Optional[torch.Tensor] = None, mask: Optional[torch.Tensor] = None):
        device = features.device

        if len(features.shape) < 3:
            raise ValueError("features must be [bsz, n_views, ...]")
        if len(features.shape) > 3:
            features = features.view(features.shape[0], features.shape[1], -1)

        batch_size = features.shape[0]
        if labels is not None and mask is not None:
            raise ValueError("Cannot define both labels and mask.")
        elif labels is None and mask is None:
            mask = torch.eye(batch_size, dtype=torch.float32, device=device)
        elif labels is not None:
            labels = labels.contiguous().view(-1, 1)
            if labels.shape[0] != batch_size:
                raise ValueError("Num of labels does not match num of features")
            mask = torch.eq(labels, labels.T).float().to(device)
        else:
            mask = mask.float().to(device)

        contrast_count = features.shape[1]
        contrast_feature = torch.cat(torch.unbind(features, dim=1), dim=0)

        if self.contrast_mode == "one":
            anchor_feature = features[:, 0]
            anchor_count = 1
        elif self.contrast_mode == "all":
            anchor_feature = contrast_feature
            anchor_count = contrast_count
        else:
            raise ValueError(f"Unknown contrast_mode: {self.contrast_mode}")

        anchor_dot_contrast = torch.div(torch.matmul(anchor_feature, contrast_feature.T), self.temperature)
        logits_max, _ = torch.max(anchor_dot_contrast, dim=1, keepdim=True)
        logits = anchor_dot_contrast - logits_max.detach()

        mask = mask.repeat(anchor_count, contrast_count)
        logits_mask = torch.scatter(
            torch.ones_like(mask),
            1,
            torch.arange(batch_size * anchor_count, device=device).view(-1, 1),
            0,
        )
        mask = mask * logits_mask

        exp_logits = torch.exp(logits) * logits_mask
        log_prob = logits - torch.log(exp_logits.sum(1, keepdim=True) + 1e-12)

        mean_log_prob_pos = (mask * log_prob).sum(1) / (mask.sum(1) + 1e-12)
        loss = -(self.temperature / self.base_temperature) * mean_log_prob_pos
        loss = loss.view(anchor_count, batch_size).mean()
        return loss


def kd_loss(student_logits: torch.Tensor, teacher_logits: torch.Tensor, temperature: float) -> torch.Tensor:
    q = torch.log_softmax(student_logits / temperature, dim=1)
    p = torch.softmax(teacher_logits / temperature, dim=1)
    return -(p * q).sum(dim=1).mean()


class CyclingDataIter:
    def __init__(self, loader) -> None:
        self.loader = loader
        self._iter = iter(loader)

    def next(self):
        try:
            return next(self._iter)
        except StopIteration:
            self._iter = iter(self.loader)
            return next(self._iter)


class DDDRSynTaskDataset(Dataset):
    """
    Reads synthetic images produced by the official DDDR code:
        <root>/task_<task_id>/<class_id>/<class_id>-<idx>.jpg

    The benchmark only uses the replay/classifier training phase and expects
    synthetic images to be pre-generated by the official DDDR pipeline.
    """
    def __init__(
        self,
        root: str | Path,
        dataset_name: str,
        task_id: int,
        size_per_cls: int,
        image_suffixes: Sequence[str] = (".jpg", ".jpeg", ".png"),
    ) -> None:
        self.root = Path(root) / f"task_{int(task_id)}"
        self.dataset_name = dataset_name
        self.image_size = infer_dddr_image_size(dataset_name)
        self.items: List[tuple[Path, int]] = []

        if not self.root.exists():
            return

        class_dirs = sorted([p for p in self.root.iterdir() if p.is_dir()], key=lambda p: int(p.name))
        for class_dir in class_dirs:
            class_id = int(class_dir.name)
            candidates = []
            for suffix in image_suffixes:
                candidates.extend(sorted(class_dir.glob(f"*{suffix}")))
            candidates = candidates[: int(size_per_cls)]
            for path in candidates:
                self.items.append((path, class_id))

    def __len__(self) -> int:
        return len(self.items)

    def __getitem__(self, idx: int):
        img_path, label = self.items[idx]
        image = Image.open(img_path).convert("RGB")
        if image.size != (self.image_size, self.image_size):
            image = image.resize((self.image_size, self.image_size), resample=Image.BICUBIC)
        image_np = np.array(image, dtype=np.uint8)
        image_tensor = torch.from_numpy(image_np).permute(2, 0, 1).contiguous()
        return image_tensor, int(label)


def build_task_syn_dataset(
    syn_root: str | Path,
    dataset_name: str,
    task_id: int,
    size_per_cls: int,
) -> Optional[Dataset]:
    dataset = DDDRSynTaskDataset(
        root=syn_root,
        dataset_name=dataset_name,
        task_id=task_id,
        size_per_cls=size_per_cls,
    )
    if len(dataset) == 0:
        return None
    return dataset


def build_concat_syn_dataset(
    syn_root: str | Path,
    dataset_name: str,
    task_ids: Sequence[int],
    size_per_cls: int,
) -> Optional[Dataset]:
    datasets = []
    for task_id in task_ids:
        ds = build_task_syn_dataset(
            syn_root=syn_root,
            dataset_name=dataset_name,
            task_id=int(task_id),
            size_per_cls=size_per_cls,
        )
        if ds is not None:
            datasets.append(ds)
    if len(datasets) == 0:
        return None
    if len(datasets) == 1:
        return datasets[0]
    return ConcatDataset(datasets)